### ISSUE TITLE
Misleading not found text when searching.

### ISSUE THREAD

**Issue by fleeting** [akashnimare/ReadAMA#6]
If you search for anything that returns the "no AMA found" text and then go back to type something else, the text in the not found updates as you type which makes it seem like the new query is not found as well.

**Steps to reproduce**:
- Open http://akashnimare.github.io/ReadAMA/#/ and search for `test`.
- No AMA found is displayed.
- Type `wesbos`. Text says wesbos is not found before hitting search.
- Hit search and it is there.

**Comment by akashnimare** [comment]
@fleeting Yes, I am aware of this bug. I'm bit busy with other stuff these days. Are you interested in solving this?
